apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
stringData:
    storage_account: {{ .Values.storage_account }} 
    storage_account_key: {{ .Values.storage_account_key }} 
    container: {{ .Values.container }}