apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
stringData:
    thanos.yaml: |
      type: AZURE
      config:
        container: {{ .Values.container }}
        storage_account: {{ .Values.storage_account }} 
        storage_account_key: {{ .Values.storage_account_key }} 